### ISSUE TITLE
scrolling stop in middle-positions

### ISSUE THREAD

**Issue by recoverrelax** [ShawnLin013/NumberPicker#28]
scroll fast, then long press fast on some item. repeat. the scroll won't snap to the closest value

**Comment by ShawnLin013** [comment]
Fixed at v2.4.1.

**Comment by sidharthanil** [comment]
Hi, this issue is still there in the library. Can you please verify

**Comment by ShawnLin013** [comment]
Close this inactive issue for now. Please reopen this issue if are still encountering problems.
